### ISSUE TITLE
Changing name of built-in commands results in loss of function

### ISSUE THREAD

**Issue by wyrde** [EverOddish/DrFujiBot#41]
A built in command has a entry field to change its name.
Example: !pokemon to !poke
Afterwords:
!poke pikachu: no result in the console
!pokemon pikachu: no result in console

Changing the command back to !pokemon results in the command working again.

!pokemon pikachu: result pikachu's info

**Comment by EverOddish** [comment]
Fixed in v2.0.23. Thanks for the bug report!
